# Generated by Django 6.1.1 on 2026-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
